//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfredas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alfredas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are five concepts related to each other in the life of any human being - THE GOAL ITSELF, GOAL-ORIENTED ACTIVITY, MOTIVATION, OUTCOME AND REWARD.
        ///
        ///If a person has set a goal for himself/herself and is well motivated while performing a goal-oriented activity, he/she will achieve results and will be awarded for this. Inner motivation is the main driving force which helps achieve the desired goal.
        ///
        ///It is absolutely necessary that the goals of a team or a company also become the personal goals of its  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutEN {
            get {
                return ResourceManager.GetString("AboutEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEIKLA,  TIKSLAS,  MOTYVACIJA,  REZULTATAS,  ATLYGINIMAS - tai penkios sąvokos, kurios paliečia kiekvieną žmogų. Kiekvienas, kuris vykdo veiklą, turi tikslą, vidinę motyvaciją, pasiekia rezultatus ir už tai jam būna atlyginta. Vidinė motyvacija - pagrindinis tikslo siekimo variklis.
        ///
        ///Tam, kad įmonės ar komandos tikslai taptų kiekvieno jos nario tikslais, būtina, kad kiekvienas dalyvautų šių tikslų formavime, nustatyme. Tuomet, įgyvendinant užsibrėžtus tikslus, atsiranda vidinė motyvacija, kuri padeda pasi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutLT {
            get {
                return ResourceManager.GetString("AboutLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДЕЯТЕЛЬНОСТЬ, ЦЕЛЬ, МОТИВАЦИЯ, РЕЗУЛЬТАТ, ВОЗНАГРАЖДЕНИЕ – это пять понятий, которые касаются каждого человека. Каждый, кто осуществляет деятельность, имеет цель, внутреннюю мотивацию, достигает результатов и получает за это вознаграждение. Внутренняя мотивация – основной двигатель достижения цели.
        ///
        ///
        ///Для того, чтобы цель команды стала целью каждого ее члена, необходимо, чтобы каждый принял участие в формировании, определении этих целей. Тогда при реализации поставленных целей возникает внутренняя мотивац [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutRU {
            get {
                return ResourceManager.GetString("AboutRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon dd66325dba3d29ac {
            get {
                object obj = ResourceManager.GetObject("dd66325dba3d29ac", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpEN {
            get {
                object obj = ResourceManager.GetObject("HelpEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpLT {
            get {
                object obj = ResourceManager.GetObject("HelpLT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HelpRU {
            get {
                object obj = ResourceManager.GetObject("HelpRU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
