//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfredas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Darbuotoju lentele:
3
Marko,1000,1163,1023,3186
Employee 2,2000,0,0,2000
Employee 3,3000,0,0,3000
Rodikliu lentele:
4
PROFIT,100000,121000,130000,1200
COSTS,500000,480000,450000,800
Indicator 3,2,4,2.4,2
Indicator 4,3,6,3.6,3
Uzduociu lentele:
5
RELATIONSHIP WITH...,11,9
CUTTING ON THE RET...,9,5
IMPROVING PROFESS...,7,6
TASK 4,8,7
TASK 5,9,8
Archyvo lentele:
3
Marko,1000,1163,1023,3186,2014.06.16
Employee 2,2000,0,0,2000,2014.06.16
Employee 3,3000,0,0,3000,2014.06.16")]
        public string DB {
            get {
                return ((string)(this["DB"]));
            }
            set {
                this["DB"] = value;
            }
        }
    }
}
